nav:
  - "Intro.md"
  - "Module 1: Key Concepts"
    - "Overview of Robotics Techniques.md"
    - "Overview of Self-Driving Cars.md"
  - "Module 2: Advanced Topics"
  - "Module 3: Applications and Case Studies"