site_url: https://amelia-ng.github.io/handbook/
use_directory_urls: true

site_name: AI in Automotive Handbook


theme:
  name: swan

  palette:

    - scheme: default
      primary: black
      accent: indigo

  font:
    text: Lora
    code: JetBrains Mono

  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - content.code.copy
    - navigation.footer

plugins:
  - search
  - awesome-nav

markdown_extensions:

  - tables
  - toc:
      permalink: true
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight

  - pymdownx.arithmatex:
      generic: true

extra_javascript:

  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js



extra_css:
  - stylesheets/extra.css
 
