site_url: https://amelia-ng.github.io/interview-prep/
use_directory_urls: false

site_name: Interview Handbook for Data Science, Machine Learning, and AI

site_description: With an application for Automotive industry

theme:
  name: material

  palette:

    - scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  font:
    text: Lora
    code: JetBrains Mono

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.expand
    - navigation.tracking
    - navigation.path
    - content.code.copy
    - navigation.footer

plugins:
  - search
  - awesome-nav

markdown_extensions:

  - tables
  - toc:
      permalink: true
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight

  - pymdownx.arithmatex:
      generic: true

extra_javascript:

  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js



extra_css:
  - stylesheets/extra.css
 
